kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node
    commands:
      - npm install

  - name: test
    image: node
    commands:
      - npm test

trigger:
  event:
    - push
    - pull_request
